version: 1.0.{build}

image:
  - Visual Studio 2015
  - Ubuntu
  - macos

for:
-
  matrix:
    only:
      - image: Ubuntu

  environment:
    GENERATOR : "Unix Makefiles"
    EXTENTION: "so"
    LINUX_ONLY: 'cp "build/mimalloc/libmimalloc.$EXTENTION.1.2" dist/libs'

  install:
  - git submodule update --init --recursive
  - sudo add-apt-repository ppa:beineri/opt-qt-5.13.2-bionic
  - sudo apt-get update
  - sudo apt install -y make g++ xvfb qt513base qt513multimedia qt513declarative mesa-common-dev libglu1-mesa-dev
-
  matrix:
    only:
      - image: macos

  install:
  - git submodule update --init --recursive
  - brew install qt
  
  environment:
    LDFLAGS: "-L/usr/local/opt/qt/lib"
    CPPFLAGS: "-I/usr/local/opt/qt/include"
    Qt5Widgets_DIR: "/usr/local/opt/qt/lib/cmake/Qt5Widgets"
    Qt5Test_DIR: "/usr/local/opt/qt/lib/cmake/Qt5Test"
    Qt5Core_DIR: "/usr/local/opt/qt/lib/cmake/Qt5Core"
    Qt5_DIR: "/usr/local/opt/qt/lib/cmake"
    Qt5Concurrent_DIR: "/usr/local/opt/qt/lib/cmake/Qt5Concurrent"
    Qt5Gui_DIR: "/usr/local/opt/qt/lib/cmake/Qt5Gui"
    GENERATOR : "Unix Makefiles"
    EXTENTION: "dylib"
    LINUX_ONLY: "echo hi"

-
  matrix:
    only:
      - image: Visual Studio 2015
  
  install:
  - git submodule update --init --recursive
  - choco install zip
  - set PATH=C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\bin;%PATH:C:\Program Files\Git\usr\bin;=%
  
  environment:
    Qt5_DIR: 'C:\Qt\5.13.2\mingw73_64'
    GENERATOR : "MinGW Makefiles"
    EXTENTION: "dll"
    LINUX_ONLY: "echo hi"

build_script:
- C:\Program Files\Git\usr\bin\bash.exe generate.sh

artifacts:
  - path: "dist.zip"
    name: "dist.zip"
