version: 1.0.{build}

image:
  - Visual Studio 2019
  - Ubuntu
  - macos

for:
  - matrix:
      only:
        - image: Ubuntu

    environment:
      GENERATOR: "Unix Makefiles"
      EXTENTION: "so"
      LINUX_ONLY: 'cp build/mimalloc/libmimalloc.so.1.2 dist/libs'

    install:
      - git submodule update --init --recursive
      - sudo add-apt-repository ppa:beineri/opt-qt-5.13.2-bionic
      - sudo apt-get update
      - sudo apt install -y make g++ xvfb qt513base qt513multimedia qt513declarative mesa-common-dev libglu1-mesa-dev

    build_script:
      - bash generate.sh

  - matrix:
      only:
        - image: macos

    install:
      - git submodule update --init --recursive
      - brew install qt

    environment:
      LDFLAGS: "-L/usr/local/opt/qt/lib"
      CPPFLAGS: "-I/usr/local/opt/qt/include"
      Qt5Widgets_DIR: "/usr/local/opt/qt/lib/cmake/Qt5Widgets"
      Qt5Test_DIR: "/usr/local/opt/qt/lib/cmake/Qt5Test"
      Qt5Core_DIR: "/usr/local/opt/qt/lib/cmake/Qt5Core"
      Qt5_DIR: "/usr/local/opt/qt/lib/cmake"
      Qt5Concurrent_DIR: "/usr/local/opt/qt/lib/cmake/Qt5Concurrent"
      Qt5Gui_DIR: "/usr/local/opt/qt/lib/cmake/Qt5Gui"
      GENERATOR: "Unix Makefiles"
      EXTENTION: "dylib"
      LINUX_ONLY: "echo hi"

    build_script:
      - bash generate.sh

  - matrix:
      only:
        - image: Visual Studio 2019

    install:
      - git submodule update --init --recursive
      - choco install zip
      - set PATH=C:\Qt\Tools\mingw730_64\bin;%PATH:C:\Program Files\Git\usr\bin;=%
      - set PATH=%Qt5_DIR%;%Qt5_DIR%\bin;%PATH%

    environment:
      Qt5_DIR: 'C:\Qt\5.13.2\mingw73_64'
      GENERATOR: "MinGW Makefiles"
      EXTENTION: "dll"
      LINUX_ONLY: "echo hi"
      ARCH: "x86_64"

    build_script:
      - ps: mkdir build
      - ps: cd build
      - cmake .. -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles"
      - cmake --build . --target stanford "-j4"
      - set PATH=C:\Program Files\Git\usr\bin;%PATH%
      - bash generate-win.sh

artifacts:
  - path: "dist.zip"
    name: "dist.zip"
