enable_testing()
find_package(Qt5Test REQUIRED)
find_package(OpenMP)
if (OPENMP_FOUND)
    set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
    set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
    set (CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
endif()
function(unit_test subdir name)
    add_executable(test_${name} tests/${subdir}/test_${name}.cpp)
    add_test(test_${name}_run test_${name})
    target_link_libraries(test_${name} stanford Qt5::Test)
endfunction()
unit_test(util strlib)
unit_test(collections vector)
unit_test(sync locks)
