version: 2
jobs:
  buildtest:
    docker:
    - image: archlinux/base
    steps:
    - checkout
    - run:
        no_output_timeout: 3m
        command: |
          pacman --noconfirm -Syyu
          pacman --noconfirm -S cmake qt5-base gcc git qt5-multimedia xorg-server-xvfb make
          git submodule init
          git submodule update
    - run:
        no_output_timeout: 3m
        command: |
          mkdir dist
          cd dist
          cmake ..
          make
          xvfb-run make test

workflows:
  version: 2
  build_and_test:
    jobs:
    - buildtest
