version: 2
jobs:
  buildtest:
    docker:
    - image: ubuntu:disco
    steps:
    - checkout
    - run:
        no_output_timeout: 3m
        command: |
          apt-get -q -y update
          apt-get -q -y install cmake qtbase5-dev xvfb git qtmultimedia5-dev g++-9
          git submodule init
          git submodule update
    - run:
        no_output_timeout: 3m
        command: |
          mkdir dist
          cd dist
          cmake .. -D CMAKE_C_COMPILER=/usr/bin/gcc-9 -D CMAKE_CXX_COMPILER=/usr/bin/g++-9
          make
          make test

workflows:
  version: 2
  build_and_test:
    jobs:
    - buildtest
